[package]
name = "fluffe-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11", features = ["utils", "cache"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
rust-i18n = "2"
dotenv = "0.15.0"
sea-orm = { version = "^0.12.0", features = [ "sqlx-postgres", "runtime-async-std-native-tls", "macros" ] }
thiserror = "1.0"
rand = "0.8.5"
